#pragma once

#include <iostream>
#include <string>
#include <map>
#include <fstream>
#include <sstream>
#include <cctype>
#include <regex>
#include <vector>
#include <set>
#include <iomanip>

using std::map;
using std::string;
using std::cin;
using std::cout;
using std::endl;
using std::ifstream;
using std::ofstream;
using std::stringstream;
using std::ostringstream;
using std::isalpha;
using std::remove_if;
using std::regex;
using std::regex_search;
using std::vector;
using std::set;
using std::left;
using std::right;
using std::setw;